### ISSUE TITLE
Some advice from "Doug, the man, the legend, the penis"

### ISSUE THREAD

**Issue by snoopdouglas** [lewieallen/pianothingy-MVP#7]
- `gh-pages` is now your master branch
- Add one thing per feature branch
- Pull request shit into `gh-pages`
- Then once you've pull requested and merged, delete the feature branch
- Feel free to change the issue title if you like ;)
- Close this issue once you've both seen it
- Sorry, my willy is quite small actually

**Comment by harrygfox** [comment]
@snoopdouglas 

# Thanks pal

### GTFO

*jk* I appreciate the fettling you've done.

**Comment by harrygfox** [comment]
@lewieallen

**Comment by snoopdouglas** [comment]
Lol kthx xoxoxox

If you wanna remove me as collab thas kl
